DATALOADER:
  AUGMENT: heavy
  NUM_WORKERS: 8
  SAMPLER: weighted
  SAMPLER_WEIGHTS: datasets/train_split_0_weights.pickle
  SIZE_DIVISIBILITY: 0
DATASETS:
  TEST: test
  TEST_LABEL: kaggle/sample_submission.csv
  TEST_ROOT: kaggle/test
  TRAIN: train
  TRAIN_LABEL: datasets/train_split_0.csv
  TRAIN_ROOT: datasets/train
  VALID: valid
  VALID_LABEL: datasets/valid_split_0.csv
  VALID_ROOT: datasets/train
INPUT:
  MAX_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MIN_SIZE_TRAIN: 512
  TEST_PIXEL_MEAN:
  - 0.0591
  - 0.0453
  - 0.0407
  - 0.0592
  TEST_PIXEL_STD:
  - 0.1037
  - 0.0798
  - 0.1066
  - 0.0988
  TRAIN_PIXEL_MEAN: &id001
  - 0.0874
  - 0.0518
  - 0.0514
  - 0.0793
  TRAIN_PIXEL_STD: &id002
  - 0.1273
  - 0.0805
  - 0.1309
  - 0.1174
  VALID_PIXEL_MEAN: *id001
  VALID_PIXEL_STD: *id002
MODEL:
  DEVICE: cuda
  LOSS: macro f1
  LOSS_WEIGHT:
  - 1.0
  - 3.28
  - 2.03
  - 3.19
  - 2.77
  - 2.61
  - 3.08
  - 2.17
  - 5.94
  - 6.01
  - 6.08
  - 3.64
  - 3.62
  - 4.03
  - 3.45
  - 7.15
  - 4.16
  - 5.23
  - 3.77
  - 3.12
  - 5.25
  - 1.8
  - 3.41
  - 2.08
  - 5.23
  - 1.0
  - 4.75
  - 6.44
  META_ARCHITECTURE: ProteinResnet
  NAME: resnet18_maxavg
  NUM_CLASS: 28
  WEIGHT: ''
OUTPUT_DIR: dump/res18_cv0
SOLVER:
  BASE_LR: 0.04
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 10
  FINETUNE: 'on'
  FINETUNE_EPOCH: 3
  FINETUNE_LR: 0.05
  GAMMA: 0.5
  IMS_PER_BATCH: 128
  MIXUP: 'off'
  MOMENTUM: 0.9
  OPTIMIZER: sgd
  PATIENCE: 10
  SCHEDULER: StepLR
  STEPS:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  STEP_SIZE: 8
  TRAIN_EPOCH: 100
  T_MAX: 10
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0
TEST:
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 64
  TTA: 'on'
VERSION: 1
